# Profile dev : pour faire tourner en local sans schéma préexistant
# Utiliser : mvn spring-boot:run -Dspring-boot.run.profiles=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Valider la connexion DB au démarrage
spring.datasource.validation-query=SELECT 1
